# Generated by Django 2.0.3 on 2018-03-13 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dokładnie 4 znaki, tylko litery lub cyfry', max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='Wpisz dokładnie 4 znaki. Dozwolone są tylko litery (bez polskich znaków) oraz cyfry.', regex='^[a-zA-Z0-9]{4}$')], verbose_name='Nazwa')),
            ],
            options={
                'verbose_name_plural': 'Typy',
                'verbose_name': 'Typ',
            },
        ),
    ]
