# Generated by Django 2.0.3 on 2018-03-13 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Dokładnie 4 znaki, tylko litery lub cyfry', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Wpisz dokładnie 4 znaki. Dozwolone są tylko litery (bez polskich znaków) oraz cyfry.', regex='^[a-zA-Z0-9]{4}$')], verbose_name='Nazwa'),
        ),
    ]
